<a href="https://colab.research.google.com/github/RitekPillai/CGPracticals/blob/main/Page2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practical9B

In [11]:
import numpy as np

def boundaryfill(image, x, y, fill_color, boundary_color):

    rows, cols = image.shape  # Get image dimensions

    # checking for the out of bonds and checking if the x,y is equal to fillcolor(which is already filled ) or boundary_color
    if 0 <= x < cols and 0 <= y < rows and image[y, x] != fill_color and image[y, x] != boundary_color:
        image[y, x] = fill_color
        boundaryfill(image, x + 1, y, fill_color, boundary_color)
        boundaryfill(image, x - 1, y, fill_color, boundary_color)
        boundaryfill(image, x, y + 1, fill_color, boundary_color)
        boundaryfill(image, x, y - 1, fill_color, boundary_color)
    return image

image = np.array([
    [0, 0, 0, 0, 0, 0, 0],
    [0, 1, 1, 1, 1, 0, 0],
    [0, 1, 0, 0, 1, 0, 0],
    [0, 1, 0, 0, 1, 0, 0],
    [0, 1, 1, 1, 1, 0, 0]
])

print("Original Image:")
print(image)
print("New Image:")
print(boundaryfill(image, 1, 1, 5, 0))

Original Image:
[[0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0]
 [0 1 0 0 1 0 0]
 [0 1 0 0 1 0 0]
 [0 1 1 1 1 0 0]]
New Image:
[[0 0 0 0 0 0 0]
 [0 5 5 5 5 0 0]
 [0 5 0 0 5 0 0]
 [0 5 0 0 5 0 0]
 [0 5 5 5 5 0 0]]
